services:
    - type: web
      name: Peepalytics_test
      runtime: python
      repo: https://github.com/Couzy21/Peepalytics_test
      plan: free
      envVars:
          - key: DEFAULT_CURRENCY
            sync: false
          - key: ENV
            sync: false
          - key: SQUARE_APP_ID
            sync: false
          - key: SQUARE_ACCESS_TOKEN
            sync: false
          - key: DEBUG
            sync: false
          - key: DATABASE_URL
            sync: false
          - key: SECRET_KEY
            sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn payments.wsgi --bind 0.0.0.0:$PORT
version: "1"
